"""Issue 80: the public front page, generated from the fixture.

A stranger lands here knowing nothing. They do not know what demurrage is, they have
never heard of 46 CFR Part 541, and "recompute the days" is not a sentence yet. So the
page spends its first two sentences on the problem and nothing on the product.

The proof is the same day grid the intake leads with, produced by the same call, so
this page cannot show a number the engine disagrees with. ``web/`` is generated by
``make landing`` and never hand-written, which means a landing page whose figures were
typed into a template is not a thing that can happen here. That is the whole reason the
page is generated rather than authored.

On the honesty section at the bottom
-----------------------------------

It lists what does not exist yet, including that there is no hosted version and no
customer has used this. A landing page that only says what is good about itself is
indistinguishable from a landing page that is making things up, and this project has
nothing to trade its credibility for. The list is short because the project is early,
and it would grow honestly as the project grows.
"""

from __future__ import annotations

from quayline.web.design import stylesheet
from quayline.web.example import day, example_audit, money
from quayline.web.intake import COMPONENT_CSS, day_cells, esc, ledger, legend, rail

LANDING_CSS = """
.wrap { max-width: 62rem; margin: 0 auto; padding: var(--pad); }
.bar {
  display: flex; flex-wrap: wrap; gap: var(--gap);
  justify-content: space-between; align-items: baseline;
  padding-bottom: var(--gap-tight); border-bottom: 1px solid var(--edge);
}
h2 {
  font-family: var(--font-stencil); font-weight: var(--weight-stencil);
  font-size: clamp(1.15rem, 2.6vw, 1.5rem); letter-spacing: -0.02em;
  margin: var(--gap-loose) 0 0.5rem;
}
.prose { max-width: var(--measure); }
.prose p { margin: 0 0 0.9rem; }
.plain { color: var(--slate); }

/* The proof sits in the same grid the intake uses, so the two pages cannot drift into
   looking like different products. */
.proof { margin-top: var(--gap-loose); }

/* The rail is a narrow column on the intake, where it sits beside the argument. Here it
   is full width, and seven stacked rows of it push the day grid below the fold. Laying
   the rows out as columns keeps the block reading as a manifest header rather than as
   the first thing on the page. */
.proof .rail dl {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
}
.proof .rail div { border-bottom: 0; border-right: 1px solid var(--edge); }

.facts { margin: var(--gap-loose) 0 0; padding: 0; display: grid; gap: 0.15rem; }
.facts div { display: flex; gap: var(--gap); padding: 0.5rem 0; border-bottom: 1px solid var(--edge); }
.facts dt { margin: 0; color: var(--slate); flex: 0 0 13rem; }
.facts dd { margin: 0; }

.foot { margin-top: var(--pad); padding-top: var(--gap); border-top: 1px solid var(--edge); }
.foot p { max-width: var(--measure); color: var(--slate); margin: 0 0 0.7rem; }
code { font-family: var(--font-data); color: var(--chalk); }
@media (max-width: 40rem) {
  .facts div { flex-direction: column; gap: 0.15rem; }
  .facts dt { flex: none; }
}
"""

#: What exists, and what does not. Stated as lists because a paragraph invites a reader
#: to skim past the half they did not want.
EXISTS = [
    "The engine. It reads a born-digital carrier PDF, pulls the disclosures, and "
    "recomputes the charge one day at a time under 46 CFR Part 541.",
    "One transcribed carrier tariff, Maersk, taken from Maersk's own published "
    "document and carrying its effective date.",
    "A dispute packet. The findings, the recomputation, and the day strip, rendered "
    "as a letter you can send.",
    "A local intake. It runs on your machine, on 127.0.0.1, and refuses any other interface.",
]

MISSING = [
    "No hosted version. There is no site to sign up for and nothing to upload to. It "
    "runs on your own machine, and that is the honest state of it.",
    "No customer. Nobody has used this on a real account yet, so there is no recovery "
    "rate to quote and no case study.",
    "One carrier's rates. A carrier we hold a day-count rule for but no transcribed "
    "rate still gets its days recomputed and not its money, and the answer says so. "
    "A carrier with no day-count rule cannot be audited at all, and says that too.",
    "No filing. This finds the error and writes the letter. It does not submit to a "
    "carrier or to the FMC.",
]


def _facts(pairs: list[tuple[str, str]]) -> str:
    rows = "".join(
        f'<div><dt class="stencil">{esc(k)}</dt><dd class="data">{esc(v)}</dd></div>'
        for k, v in pairs
    )
    return f'<dl class="facts">{rows}</dl>'


def _items(entries: list[str]) -> str:
    return '<ul class="plain">' + "".join(f"<li>{esc(e)}</li>" for e in entries) + "</ul>"


def landing_page() -> str:
    """The public front page, with the proof computed rather than typed."""
    strip, result, rail_pairs = example_audit()
    allowance = dict(rail_pairs)["free time"]
    body = (
        '<div class="wrap">\n'
        '<div class="bar">'
        '<span class="stencil">Quayline</span>'
        '<span class="stencil">46 CFR Part 541</span>'
        "</div>\n"
        "<h1>A container sits. The clock runs. Somebody pays.</h1>\n"
        '<div class="prose">\n'
        "<p>When your box is sitting at a port or a rail yard longer than it should be, "
        "the terminal charges you for the delay. That bill is demurrage when the box is "
        "still there, and detention when it has left and is not returned. Both are "
        "charged per day, and both arrive as one number on one invoice.</p>\n"
        "<p>The carrier is required to publish the rule they are charging you by: the "
        "free days, the rate, and the dates they say they counted. Almost nobody checks "
        "the bill against that rule. When they do, the arithmetic is often wrong, "
        "usually by a day or two and usually in the carrier's favour.</p>\n"
        "</div>\n"
        '<div class="proof">\n'
        "<h2>The worked example, day by day</h2>\n"
        f"{rail(rail_pairs)}\n"
        f"{day_cells(strip.days)}\n"
        f"{legend()}\n"
        f"{ledger(money(result.demanded_total), money(result.recomputed_total), money(result.variance))}\n"
        "</div>\n"
        "<h2>Why the ninth day is the argument</h2>\n"
        '<div class="prose">\n'
        f"<p>The rule the carrier published allows {esc(allowance)} of free time, and "
        f"it says that free time ended on {esc(day(strip.declared_free_time_end))}. "
        f"Counting the days it discloses itself puts the end at "
        f"{esc(day(strip.recomputed_free_time_end))}. The carrier billed through the "
        f"day after that, and charged for the day in between.</p>\n"
        "<p>That is the whole dispute. Not a rounding argument and not a complaint "
        "about the rate: the carrier counted one day more than its own rule allows. "
        "The recomputation is reproducible from the invoice, which is what makes it "
        "worth sending.</p>\n"
        "</div>\n"
        "<h2>What this does today</h2>\n"
        f"{_items(EXISTS)}\n"
        "<h2>What this does not do</h2>\n"
        f"{_items(MISSING)}\n"
        '<div class="foot">\n'
        f"<p>{
            esc(
                'The days above are computed from a synthetic invoice carrying one '
                'real transcribed Maersk rate. It is not a client, and no recovery rate '
                'is claimed anywhere on this site.'
            )
        }</p>\n"
        "<p>To run it yourself: <code>quayline serve</code>, then open the address it "
        "prints. It binds to 127.0.0.1 and refuses any other interface, keeps no "
        "account, writes nothing to disk, and logs no request line. To see how far the "
        "rate data reaches, run <code>quayline coverage</code>.</p>\n"
        "</div>\n"
        "</div>"
    )
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>Quayline: demurrage and detention, recomputed</title>\n"
        f'<meta name="description" content="Recomputes a U.S. ocean demurrage or '
        f"detention invoice one day at a time, from the disclosures the carrier was "
        f'required to publish.">\n'
        f"<style>{stylesheet()}{COMPONENT_CSS}{LANDING_CSS}</style>\n"
        "</head>\n"
        f"<body>\n{body}\n</body>\n"
        "</html>\n"
    )


__all__ = ["EXISTS", "LANDING_CSS", "MISSING", "landing_page"]
